// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	AlbumID  int32  `json:"album_id"`
	Title    string `json:"title"`
	ArtistID int32  `json:"artist_id"`
}

type Artist struct {
	ArtistID int32   `json:"artist_id"`
	Name     *string `json:"name"`
}

type Customer struct {
	CustomerID   int32   `json:"customer_id"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	Company      *string `json:"company"`
	Address      *string `json:"address"`
	City         *string `json:"city"`
	State        *string `json:"state"`
	Country      *string `json:"country"`
	PostalCode   *string `json:"postal_code"`
	Phone        *string `json:"phone"`
	Fax          *string `json:"fax"`
	Email        string  `json:"email"`
	SupportRepID *int32  `json:"support_rep_id"`
}

type Employee struct {
	EmployeeID int32            `json:"employee_id"`
	LastName   string           `json:"last_name"`
	FirstName  string           `json:"first_name"`
	Title      *string          `json:"title"`
	ReportsTo  *int32           `json:"reports_to"`
	BirthDate  pgtype.Timestamp `json:"birth_date"`
	HireDate   pgtype.Timestamp `json:"hire_date"`
	Address    *string          `json:"address"`
	City       *string          `json:"city"`
	State      *string          `json:"state"`
	Country    *string          `json:"country"`
	PostalCode *string          `json:"postal_code"`
	Phone      *string          `json:"phone"`
	Fax        *string          `json:"fax"`
	Email      *string          `json:"email"`
}

type Genre struct {
	GenreID int32   `json:"genre_id"`
	Name    *string `json:"name"`
}

type Invoice struct {
	InvoiceID         int32            `json:"invoice_id"`
	CustomerID        int32            `json:"customer_id"`
	InvoiceDate       pgtype.Timestamp `json:"invoice_date"`
	BillingAddress    *string          `json:"billing_address"`
	BillingCity       *string          `json:"billing_city"`
	BillingState      *string          `json:"billing_state"`
	BillingCountry    *string          `json:"billing_country"`
	BillingPostalCode *string          `json:"billing_postal_code"`
	Total             pgtype.Numeric   `json:"total"`
}

type InvoiceLine struct {
	InvoiceLineID int32          `json:"invoice_line_id"`
	InvoiceID     int32          `json:"invoice_id"`
	TrackID       int32          `json:"track_id"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	Quantity      int32          `json:"quantity"`
}

type MediaType struct {
	MediaTypeID int32   `json:"media_type_id"`
	Name        *string `json:"name"`
}

type Playlist struct {
	PlaylistID int32   `json:"playlist_id"`
	Name       *string `json:"name"`
}

type PlaylistTrack struct {
	PlaylistID int32 `json:"playlist_id"`
	TrackID    int32 `json:"track_id"`
}

type Track struct {
	TrackID      int32          `json:"track_id"`
	Name         string         `json:"name"`
	AlbumID      *int32         `json:"album_id"`
	MediaTypeID  int32          `json:"media_type_id"`
	GenreID      *int32         `json:"genre_id"`
	Composer     *string        `json:"composer"`
	Milliseconds int32          `json:"milliseconds"`
	Bytes        *int32         `json:"bytes"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
}
