// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	AlbumID  int32  `json:"album_id"`
	Title    string `json:"title"`
	ArtistID int32  `json:"artist_id"`
}

type Artist struct {
	ArtistID int32       `json:"artist_id"`
	Name     pgtype.Text `json:"name"`
}

type Customer struct {
	CustomerID   int32       `json:"customer_id"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Company      pgtype.Text `json:"company"`
	Address      pgtype.Text `json:"address"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	Country      pgtype.Text `json:"country"`
	PostalCode   pgtype.Text `json:"postal_code"`
	Phone        pgtype.Text `json:"phone"`
	Fax          pgtype.Text `json:"fax"`
	Email        string      `json:"email"`
	SupportRepID pgtype.Int4 `json:"support_rep_id"`
}

type Employee struct {
	EmployeeID int32            `json:"employee_id"`
	LastName   string           `json:"last_name"`
	FirstName  string           `json:"first_name"`
	Title      pgtype.Text      `json:"title"`
	ReportsTo  pgtype.Int4      `json:"reports_to"`
	BirthDate  pgtype.Timestamp `json:"birth_date"`
	HireDate   pgtype.Timestamp `json:"hire_date"`
	Address    pgtype.Text      `json:"address"`
	City       pgtype.Text      `json:"city"`
	State      pgtype.Text      `json:"state"`
	Country    pgtype.Text      `json:"country"`
	PostalCode pgtype.Text      `json:"postal_code"`
	Phone      pgtype.Text      `json:"phone"`
	Fax        pgtype.Text      `json:"fax"`
	Email      pgtype.Text      `json:"email"`
}

type Genre struct {
	GenreID int32       `json:"genre_id"`
	Name    pgtype.Text `json:"name"`
}

type Invoice struct {
	InvoiceID         int32            `json:"invoice_id"`
	CustomerID        int32            `json:"customer_id"`
	InvoiceDate       pgtype.Timestamp `json:"invoice_date"`
	BillingAddress    pgtype.Text      `json:"billing_address"`
	BillingCity       pgtype.Text      `json:"billing_city"`
	BillingState      pgtype.Text      `json:"billing_state"`
	BillingCountry    pgtype.Text      `json:"billing_country"`
	BillingPostalCode pgtype.Text      `json:"billing_postal_code"`
	Total             pgtype.Numeric   `json:"total"`
}

type InvoiceLine struct {
	InvoiceLineID int32          `json:"invoice_line_id"`
	InvoiceID     int32          `json:"invoice_id"`
	TrackID       int32          `json:"track_id"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	Quantity      int32          `json:"quantity"`
}

type MediaType struct {
	MediaTypeID int32       `json:"media_type_id"`
	Name        pgtype.Text `json:"name"`
}

type Playlist struct {
	PlaylistID int32       `json:"playlist_id"`
	Name       pgtype.Text `json:"name"`
}

type PlaylistTrack struct {
	PlaylistID int32 `json:"playlist_id"`
	TrackID    int32 `json:"track_id"`
}

type Track struct {
	TrackID      int32          `json:"track_id"`
	Name         string         `json:"name"`
	AlbumID      pgtype.Int4    `json:"album_id"`
	MediaTypeID  int32          `json:"media_type_id"`
	GenreID      pgtype.Int4    `json:"genre_id"`
	Composer     pgtype.Text    `json:"composer"`
	Milliseconds int32          `json:"milliseconds"`
	Bytes        pgtype.Int4    `json:"bytes"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
}
