//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Album = Album.FromSchema(schema)
	Artist = Artist.FromSchema(schema)
	Customer = Customer.FromSchema(schema)
	Employee = Employee.FromSchema(schema)
	Genre = Genre.FromSchema(schema)
	Invoice = Invoice.FromSchema(schema)
	InvoiceLine = InvoiceLine.FromSchema(schema)
	MediaType = MediaType.FromSchema(schema)
	Playlist = Playlist.FromSchema(schema)
	PlaylistTrack = PlaylistTrack.FromSchema(schema)
	Track = Track.FromSchema(schema)
}
