//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Customer struct {
	CustomerID   int32 `sql:"primary_key"`
	FirstName    string
	LastName     string
	Company      *string
	Address      *string
	City         *string
	State        *string
	Country      *string
	PostalCode   *string
	Phone        *string
	Fax          *string
	Email        string
	SupportRepID *int32
}
