//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Employee struct {
	EmployeeID int32 `sql:"primary_key"`
	LastName   string
	FirstName  string
	Title      *string
	ReportsTo  *int32
	BirthDate  *time.Time
	HireDate   *time.Time
	Address    *string
	City       *string
	State      *string
	Country    *string
	PostalCode *string
	Phone      *string
	Fax        *string
	Email      *string
}
