//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type InvoiceLine struct {
	InvoiceLineID int32 `sql:"primary_key"`
	InvoiceID     int32
	TrackID       int32
	UnitPrice     float64
	Quantity      int32
}
