//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Track struct {
	TrackID      int32 `sql:"primary_key"`
	Name         string
	AlbumID      *int32
	MediaTypeID  int32
	GenreID      *int32
	Composer     *string
	Milliseconds int32
	Bytes        *int32
	UnitPrice    float64
}
